### ISSUE TITLE
db/product

### ISSUE THREAD

**Issue by dominik-pm** [dominik-pm/ProductConfigurator#1]
# Interfaces:
## /db/product/ (GET)
> to get all products

**Request Data:**
```javascript
{
    
}
```
**Response Data:**
```javascript
[
    {
        "configId": String,
        "images": [
        String
        ],
        "name": String,
        "description": String,
        "options": [
            {
                "id": String,
                "name": String,
                "description": String
            }
        ],
        "rules": {
            "basePrice": Number,
            "defaultModel": String,
            "requirements": {
                "additionalProp1": [
            String
                ],
                "additionalProp2": [
            String
                ],
                "additionalProp3": [
            String
                ]
            },
            "incompatibilities": {
                "additionalProp1": [
            String
                ],
                "additionalProp2": [
            String
                ],
                "additionalProp3": [
            String
                ]
            },
            "groupRequirements": {
                "additionalProp1": [
            String
                ],
                "additionalProp2": [
            String
                ],
                "additionalProp3": [
            String
                ]
            },
            "priceList": {
                "additionalProp1": Number,
                "additionalProp2": Number,
                "additionalProp3": Number
            },
            "models": [
                {
                    "id": String,
                    "optionIds": [
              String
                    ],
                    "name": String,
                    "description": String
                }
            ],
            "replacementGroups": {
                "additionalProp1": [
            String
                ],
                "additionalProp2": [
            String
                ],
                "additionalProp3": [
            String
                ]
            }
        },
        "optionGroups": [
            {
                "id": String,
                "optionIds": [
            String
                ],
                "required": Boolean,
                "name": String,
                "description": String
            }
        ],
        "optionSections": [
            {
                "id": String,
                "name": String,
                "optionGroupIds": [
            String
                ]
            }
        ]
    }
]
```
**Todo:**
- [x] implement a database query that gets the products

**Test cases:**
- [x] test response data

## /db/product/[id] (GET)
> to get a specific product

**Request Data:**
```javascript
{
    
}
```
**Response Data:**
```javascript
{
    "configId": String,
    "images": [
        String
    ],
    "name": String,
    "description": String,
    "options": [
        {
            "id": String,
            "name": String,
            "description": String
        }
    ],
    "rules": {
        "basePrice": Number,
        "defaultModel": String,
        "requirements": {
            "additionalProp1": [
            String
            ],
            "additionalProp2": [
            String
            ],
            "additionalProp3": [
            String
            ]
        },
        "incompatibilities": {
            "additionalProp1": [
            String
            ],
            "additionalProp2": [
            String
            ],
            "additionalProp3": [
            String
            ]
        },
        "groupRequirements": {
            "additionalProp1": [
            String
            ],
            "additionalProp2": [
            String
            ],
            "additionalProp3": [
            String
            ]
        },
        "priceList": {
            "additionalProp1": Number,
            "additionalProp2": Number,
            "additionalProp3": Number
        },
        "models": [
            {
                "id": String,
                "optionIds": [
              String
                ],
                "name": String,
                "description": String
            }
        ],
        "replacementGroups": {
            "additionalProp1": [
            String
            ],
            "additionalProp2": [
            String
            ],
            "additionalProp3": [
            String
            ]
        }
    },
    "optionGroups": [
        {
            "id": String,
            "optionIds": [
            String
            ],
            "required": Boolean,
            "name": String,
            "description": String
        }
    ],
    "optionSections": [
        {
            "id": String,
            "name": String,
            "optionGroupIds": [
            String
            ]
        }
    ]
}
```
**Todo:**
- [x] implement a database query that get the product

**Test cases:**
- [x] test response data

## /db/product (POST)
> to add a new product to the database

**Request Data:**
```javascript
{
    "configId": String,
    "images": [
      String
    ],
    "name": String,
    "description": String,
    "options": [
        {
            "id": String,
            "name": String,
            "description": String
        }
    ],
    "rules": {
        "basePrice": Number,
        "defaultModel": String,
        "requirements": {
            "additionalProp1": [
          String
            ],
            "additionalProp2": [
          String
            ],
            "additionalProp3": [
          String
            ]
        },
        "incompatibilities": {
            "additionalProp1": [
          String
            ],
            "additionalProp2": [
          String
            ],
            "additionalProp3": [
          String
            ]
        },
        "groupRequirements": {
            "additionalProp1": [
          String
            ],
            "additionalProp2": [
          String
            ],
            "additionalProp3": [
          String
            ]
        },
        "priceList": {
            "additionalProp1": Number,
            "additionalProp2": Number,
            "additionalProp3": Number
        },
        "models": [
            {
                "id": String,
                "optionIds": [
            String
                ],
                "name": String,
                "description": String
            }
        ],
        "replacementGroups": {
            "additionalProp1": [
          String
            ],
            "additionalProp2": [
          String
            ],
            "additionalProp3": [
          String
            ]
        }
    },
    "optionGroups": [
        {
            "id": String,
            "optionIds": [
          String
            ],
            "required": Boolean,
            "name": String,
            "description": String
        }
    ],
    "optionSections": [
        {
            "id": String,
            "name": String,
            "optionGroupIds": [
          String
            ]
        }
    ]
}
```
**Response Data:**
```javascript
{

}
```
**Todo:**
- [x] save the new products configuration in the database

**Test cases:**
- [x] test request data format
- [x] test if the product is added to the database

## /db/product/[id] (DELETE)
> to delete a specific product

**Request Data:**
```javascript
{
    
}
```
**Response Data:**
```javascript
{

}
```
**Todo:**
- [x] implement a database query that deletes the product

**Test cases:**
- [x] test if deleted in database

## /db/product/ (PUT)
> to update a specific product

**Request Data:**
```javascript
{
    "configId": String,
    "images": [
      String
    ],
    "name": String,
    "description": String,
    "options": [
        {
            "id": String,
            "name": String,
            "description": String
        }
    ],
    "rules": {
        "basePrice": Number,
        "defaultModel": String,
        "requirements": {
            "additionalProp1": [
          String
            ],
            "additionalProp2": [
          String
            ],
            "additionalProp3": [
          String
            ]
        },
        "incompatibilities": {
            "additionalProp1": [
          String
            ],
            "additionalProp2": [
          String
            ],
            "additionalProp3": [
          String
            ]
        },
        "groupRequirements": {
            "additionalProp1": [
          String
            ],
            "additionalProp2": [
          String
            ],
            "additionalProp3": [
          String
            ]
        },
        "priceList": {
            "additionalProp1": Number,
            "additionalProp2": Number,
            "additionalProp3": Number
        },
        "models": [
            {
                "id": String,
                "optionIds": [
            String
                ],
                "name": String,
                "description": String
            }
        ],
        "replacementGroups": {
            "additionalProp1": [
          String
            ],
            "additionalProp2": [
          String
            ],
            "additionalProp3": [
          String
            ]
        }
    },
    "optionGroups": [
        {
            "id": String,
            "optionIds": [
          String
            ],
            "required": Boolean,
            "name": String,
            "description": String
        }
    ],
    "optionSections": [
        {
            "id": String,
            "name": String,
            "optionGroupIds": [
          String
            ]
        }
    ]
}
```
**Response Data:**
```javascript
{

}
```
**Todo:**
- [x] implement a database query that updates the product

**Test cases:**
- [x] test is updated
