### ISSUE TITLE
Backend API /products (order a product)

### ISSUE THREAD

**Issue by dominik-pm** [dominik-pm/ProductConfigurator#10]
# Interfaces:
## /products/[id] (POST)
> to order the configured product

**Request Data:**
```javascript
{
    "configurationName": String,
    "options": [String],
    "price": Number,
    "model": String
}
```
**Response Data:**
```javascript

```
**Todo:**
- [x] destruct the json object into the format that the database api wants it
- [x] calculate the price of the product (compare it to the sent price -> for test purpose to check if the frontend calculated the price correctly)
- [x] send the data to the database api

**Test cases:**
- [x] check if the json is correctly read and reformatted
