### ISSUE TITLE
db/configuration

### ISSUE THREAD

**Issue by dominik-pm** [dominik-pm/ProductConfigurator#11]
# Interfaces:
## /configuration/byWrapper (GET)
> to get a specific configuration

**Request Data:**
```javascript
{
    "configId": String,
    "savedName": String,
    "userEmail": String
}
```
**Response Data:**
```javascript
{
    "savedName": String,
    "options": [
        String
    ],
    "configId": String,
    "name": String,
    "description": String,
    "status": String,
    "date": DateTime,
    "user": {
        "userName": String,
        "userEmail": String,
        "isAdmin": Boolean
    }
}
```
**Todo:**
- [x] implement a database query that gets the required products configuration options

**Test cases:**
- [x] test response data

## /configuration/ (GET)
> to get all configurations

**Request Data:**
```javascript
{
    
}
```
**Response Data:**
```javascript
[
    {
        "savedName": String,
        "options": [
        String
        ],
        "configId": String,
        "name": String,
        "description": String,
        "status": String,
        "date": DateTime,
        "user": {
            "userName": String,
            "userEmail": String,
            "isAdmin": Boolean
        }
    }
]
```
**Todo:**
- [x] implement a database query that gets all configurations

**Test cases:**
- [x] test response data

## /configuration (POST)
> to insert a new configuration

**Request Data:**
```javascript
{
    "savedName": String,
    "options": [
      String
    ],
    "configId": String,
    "name": String,
    "description": String,
    "status": String,
    "date": DateTime,
    "user": {
        "userName": String,
        "userEmail": String,
        "isAdmin": Boolean
    }
}
```
**Response Data:**
```javascript
{

}
```
**Todo:**
- [x] implement a database query that post the configuration

**Test cases:**
- [x] test if the configuration is saved
- [x] validate the post format

## /db/configuration (DELETE)
> to delete a configuration

**Request Data:**
```javascript
{
    "configId": String,
    "savedName": String,
    "userEmail": String
}
```
**Response Data:**
```javascript
{

}
```
**Todo:**
- [x] implement a database query to delete the configuration

**Test cases:**
- [x] test if the configuration is deleted

## /configuration/[savedName] (PUT)
> to update the configuration

**Request Data:**
```javascript
{
    "savedName": String,
    "options": [
      String
    ],
    "configId": String,
    "name": String,
    "description": String,
    "status": String,
    "date": DateTime,
    "user": {
        "userName": String,
        "userEmail": String,
        "isAdmin": Boolean
    }
}
```
**Response Data:**
```javascript
{

}
```
**Todo:**
- [x] implement a database query to update the configuration

**Test cases:**
- [x] test if the configuration is updated
