### ISSUE TITLE
Product order PDF

### ISSUE THREAD

**Issue by dominik-pm** [dominik-pm/ProductConfigurator#12]
# Product order PDF
> the configuration of an ordered product is sent by mail in a pdf format

**Expected Behavior**
> whenever a user orders a product (with a valid configuration), an email with a pdf that includes the order details (configuration) is sent

**Todo:**
- [x] implement a pdf generator
- [x] implement a mail service

**Test cases:**
- [x] test if an email is sent when a user orders a product
- [x] test if the pdf shows the correct data
