### ISSUE TITLE
User Accounts

### ISSUE THREAD

**Issue by dominik-pm** [dominik-pm/ProductConfigurator#14]
# User accounts
> users can register an account

**Expected Behavior**
> when a user is registered and logged in, he can:
> - save configurations for later
> - view his saved/ordered configurations

**Todo:**
- [ ] implement a database tables for user accounts @SLeutgeb 
- [ ] implement a user login on the frontend @dominik-pm 
- [ ] implement a user page on the frontend @dominik-pm 
- [ ] implement a login and register api interface in the backend @t-scherzer 

**Test cases:**
- [ ] a user can register an account and login
- [ ] a user can see his ordered configurations in the user page
- [ ] a user can save a configuration and see it in the user page
- [ ] a user can logout
- [ ] passwords are stored as a hash in the database
