### ISSUE TITLE
Database-Backend /db/configuration

### ISSUE THREAD

**Issue by t-scherzer** [dominik-pm/ProductConfigurator#16]
# Interfaces:
## /db/configuration/ (GET)
> to get all configurations

**Request Data:**
```javascript
{
    
}
```
**Response Data:**
```javascript
[
    {
        "configId": Number,
        "name": String,
        "description": String,
        "images": [String],
        "options": [
            {
                "id": Number,
                "name": String,
                "description": String
            }
        ],
        "optionGroups": [
            {
                "id": String,
                "name": String,
                "description": String,
                "optionIds": [Number],
                "required": Boolean
            }
        ],
        "rules": [
            "basePrice": Number,
            "replacementGroups": {
                "{GROUP_ID}": ["{OPTION_ID}"]
            },
            "groupRequirements": {
                "{GROUP_ID}": [{"GROUP_ID"}]
            },
            "requirements": {
                "{OPTION_ID}": ["{OPTION_ID}"]
            },
            "incompatibilities: {
                "{OPTION_ID}": ["{OPTION_ID}"]
            },
            "priceList": {
                "{OPTION_ID}": Number
            }
        ]
    }
]
```
**Todo:**
- [ ] format the data in the correct way and send it as a response 

**Test cases:**
- [ ] test response data

## /db/configuration (POST)
> to save a new configuration with its configuration options for a new product

**Request Data:**
```javascript
{
    "name": String,
    "description": String,
    "images": [String],
    "options": [
        {
            "id": Number,
            "name": String,
            "description": String
        }
    ],
    "optionSections": [
        {
            "id": String,
            "name": String,
            "optionGroupIds": [
                "{OPTION_GROUP_ID}", "{OPTION_GROUP_ID}"
            ]
        }
    ],
    "optionGroups": [
        {
            "id": String,
            "name": String,
            "description": String,
            "optionIds": [Number],
            "required": Boolean,
            "replacement": Boolean
        }
    ],
    "rules": {
        "basePrice": Number,
        "defaultModel": "{MODEL_NAME}",
        "models:": [
            {
                "model": String,
                "options": ["{OPTION_ID}"]
            }
        ],
        "requirements": {
            "{OPTION_ID}": ["{OPTION_ID}"]
        },
        "incompatibilities": {
            "{OPTION_ID}": ["{OPTION_ID}"]
        },
        "priceList": {
            "{OPTION_ID}": Number
        }
    }
}
```
**Response Data:**
```javascript
{

}
```
**Todo:**
- [ ] destruct the json object format for the database
- [ ] check for a correct response after reloading it

**Test cases:**
- [ ] check if the json is correctly read and saved

**Comment by SLeutgeb** [comment]
siehe #11

**Comment by SLeutgeb** [comment]
siehe #1

**Comment by dominik-pm** [comment]
Auf Multi-Language Erweitert

**Comment by SLeutgeb** [comment]
see #11 
double entry
