### ISSUE TITLE
Database-Backend /db/account/configurations/

### ISSUE THREAD

**Issue by t-scherzer** [dominik-pm/ProductConfigurator#17]
# Interfaces:
## /db/account/configurations (GET)
> to get all saved configurations

**Request Data:**
```javascript
{
    
}
```
**Response Data:**
```javascript
[
    {
        "configId": Number,
        "savedName": String,
        "user": {
            "userName": String,
            "userEmail": String
        },
        "date": Date,
        "name": String,
        "description": String,
        "options": [String]
    }
]
```
**Todo:**
- [ ] send all saved configurations

**Test cases:**
- [ ] saved configurations are sent successfully

## /db/account/configurations/ (POST)
> to save a configuration to the account for further configuration later on
**Request Data:**
```javascript
{
        "configId": Number,
        "savedName": String,
        "user": {
            "userName": String,
            "userEmail": String
        },
        "date": Date,
        "name": String,
        "description": String,
        "options": [String]
}
```
**Response Data:**
```javascript
{

}
```
**Todo:**
- [ ] save the configuration

**Test cases:**
- [ ] reload the saved configuration and check for errors

## /db/account/configurations/{configId}/{savedName} (DELETE)
> to delete a saved configuration
**Request Data:**
```javascript
{
       
}
```
**Response Data:**
```javascript
{

}
```
**Todo:**
- [ ] delete the configuration

**Test cases:**
- [ ] check if configuration is deleted

**Comment by SLeutgeb** [comment]
redundant

**Comment by SLeutgeb** [comment]
siehe #11
