### ISSUE TITLE
db/booking

### ISSUE THREAD

**Issue by SLeutgeb** [dominik-pm/ProductConfigurator#20]
# Interfaces (/booking):
## /booking/[id]
> to get the configuration options of a specific product (id)

**Request Data:**
```javascript
{
    
}
```
**Response Data:**
```javascript
{
    "id": Number,
    "customer": Number,
    "configId": Number,
    "config": {
        "id": Number,
            "customer": Number,
                "product": {
            "productNumber": String,
                "price": Number,
                    "category": String,
                        "infos": {
                "name": String,
                    "description": String
            }
        },
        "options": [
            {
                "configId": Number,
                "optionField": {
                    "id": Number,
                    "type": String,
                    "required": Boolean,
                    "infos": {
                        "name": String,
                        "description": String
                    }
                },
                "children": [
                    {
                        "configId": Number,
                        "optionField": {
                            "id": Number,
                            "type": String,
                            "required": Boolean,
                            "infos": {
                                "name": String,
                                "description": String
                            }
                        },
                        "children": [],
                        "selected": [
                            {
                                "productNumber": String,
                                "price": Number,
                                "category": String,
                                "infos": {
                                    "name": String,
                                    "description": String
                                }
                            }
                        ]
                    }
                ],
                "selected": []
            }
        ]
    }
}
```
**Todo:**
- [ ] implement a database query that gets the required Booking information

**Test cases:**
- [ ] test response data

## /booking/getByCustomer/[customerId]
> get Bookings from a specific customer

**Request Data:**
```javascript
{

}
```
**Response Data:**
```javascript
[
    {
        "id": Number,
        "customer": Number,
        "config": Number
    }
]
```
**Todo:**
- [ ] implement a database query that gets the required Booking information from a customer

**Test cases:**
- [ ] test response data

## /booking (POST)
> Post a new Booking

**Request Data:**
```javascript
    {
    "id": Number,
     "customer": Number,
     "configId": Number,
      "config": {
        "id": Number,
            "productNumber": String,
                "customer": Number,
                    "configurationHasOptionFields": [
                        {
                            "configId": Number,
                            "optionFieldId": Number,
                            "optionField": {
                                "id": Number,
                                "type": String,
                                "required": Boolean,
                                "optionFieldHasLanguages": [
                                    {
                                        "optionFieldId": Number,
                                        "language": String,
                                        "name": String,
                                        "description": String
                                    }
                                ]
                            },
                            "Children": [
                                String
                            ],
                            "Selected": [
                                {
                                    "productNumber": String,
                                    "price": Number,
                                    "category": String,
                                    "buyable": Boolean,
                                    "pictures": [
                                        {
                                            "id": Number,
                                            "productNumber": String,
                                            "url": String
                                        }
                                    ],
                                    "productHasLanguages": [
                                        {
                                            "productNumber": String,
                                            "language": String,
                                            "name": String,
                                            "description": String
                                        }
                                    ],
                                    "productsHasOptionFields": [
                                        {
                                            "productNumber": String,
                                            "optionFields": Number,
                                            "dependencyType": String,
                                            "optionField": {
                                                "id": Number,
                                                "type": String,
                                                "required": Boolean,
                                                "optionFieldHasLanguages": [
                                                    {
                                                        "optionFieldId": Number,
                                                        "language": String,
                                                        "name": String,
                                                        "description": String
                                                    }
                                                ]
                                            },
                                            "product": String
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
    }
}
```
**Response Data:**
```javascript
{

}
```
**Todo:**
- [ ] implement a database query that saves the new Booking information

**Test cases:**
- [ ] test if saved

**Comment by SLeutgeb** [comment]
Irrelevant
