### ISSUE TITLE
Frontend Product Configuration

### ISSUE THREAD

**Issue by dominik-pm** [dominik-pm/ProductConfigurator#5]
# Frontend Product Configuration
> to configure a certain product

**Expected Behavior**
> when clicking on a product, a page with all the configuration possibilities should shown
> 
> the user can configure the product based on the configuration rules of the product
>
> when the user finishes configuring, he can send the configuration to the backend

**Todo:**
- [ ] implement an http-request that gets the configuration for the clicked on product (with an ID)
- [x] display the configuration options in their option group
- [x] implement the logic for dependent options
- [x] implement the logic for dependent groups
- [ ] implement an http-request (POST) that sends the configuration to the backend

**Test cases:**
- [ ] test error handling when requesting the configuration data
    - [ ] when no connection to the backend can be established (timeout)
    - [ ] when the wrong data is sent or is in the wrong format
- [x] a products configuration page can be shown
- [ ] test error handling when sending the configuration
  - [ ] when no connection to the backend can be established (timeout)
  - [ ] when the wrong data is sent or is in the wrong format
