### ISSUE TITLE
Frontend Show Ordered Products

### ISSUE THREAD

**Issue by dominik-pm** [dominik-pm/ProductConfigurator#6]
# Frontend Show Ordered Products
> list configurated products that have already been ordered

**Expected Behaviour**
> on a seperated page (only visible by admins) you can see all ordered products
> 
> if the user clicks on a product, the configuration page is shown but the configurations are locked in
>
> the user can change the configuration of the product when clicking "edit configuration"

**Todo:**
- [ ] implement an http-request that gets all the orderd/saved products

**Test cases:**
- [ ] test error handling when requesting the data
    - [ ] when no connection to the backend can be established (timeout)
    - [ ] when the wrong data is sent or is in the wrong format
- [ ] product orders are shown
- [ ] locked configuration page is shown with the products configuration
