### ISSUE TITLE
Product Importer Basic

### ISSUE THREAD

**Issue by dominik-pm** [dominik-pm/ProductConfigurator#7]
# Product Importer Basic
> to read a CSV-file with a products configuration options and send that data to the backend

**Expected Behaviour**
> a small program (windows forms) that can import a CSV-file is shown
> 
> when imported, the program can send a request to the backend

**Todo:**
- [ ] think of a format to save the configuration options for a product into a CSV-file
- [ ] write a small program, that reads the CSV-file
- [ ] send the read data to the backend (/configuration/new)

**Test cases:**
- [ ] test error handling when requesting the data
    - [ ] when no connection to the backend can be established (timeout)
    - [ ] when the wrong data is sent or is in the wrong format
- [ ] the CSV-File is read correctly
- [ ] test error handling when there is something wrong with the CSV data
- [ ] test if the data is really sent to the backend

**Comment by dominik-pm** [comment]
will be in the frontend
