### ISSUE TITLE
Product Importer Advanced

### ISSUE THREAD

**Issue by dominik-pm** [dominik-pm/ProductConfigurator#8]
# Product Importer Advanced
> to create a new product including its configuration on the frontend

**Expected Behaviour**
> on the frontend there is a page (only accessible with permission *TODO*) where you can create a product
> 
> when the product is fully configured (options, details, images, ...) the user can send it to the backend

**Todo:**
- [ ] implement a page where you can configure a product
  - [ ] basic information (title, description, image)
  - [ ] add new options
- [ ] implement an http-request that sends the new product to the backend (/configuration/new)

**Test cases:**
- [ ] test error handling when requesting the data
    - [ ] when no connection to the backend can be established (timeout)
    - [ ] when the wrong data is sent or is in the wrong format
- [ ] a product with multiple options including dependencies of these options can be configured
- [ ] the new product is shown on the main page and can also be configured
