### ISSUE TITLE
Backend API /configuration

### ISSUE THREAD

**Issue by dominik-pm** [dominik-pm/ProductConfigurator#9]
# Interfaces:
## /configuration/[id]
> to get the configuration options of a specific product (id)

**Request Data:**
```javascript
{
    
}
```
**Response Data:**
```javascript
{
    "configId": String,
    "name": String,
    "description": String,
    "images": [String],
    "options": [
        {
            "id": Number,
            "name": String,
            "description": String
        }
    ],
    "optionGroups": [
        {
            "id": String,
            "name": String,
            "description": String,
            "optionIds": [Number],
            "required": Boolean
        }
    ],
    "optionSections": [
        {
            "id": String,
            "name": String,
            "optionGroupIds": [Number]
        },
    ],
    "rules": [
        "basePrice": Number,
        "defaultModel": "{MODEL_NAME}",
        "models:" [
            {
                "modelName": String,
                "options": ["{OPTION_ID}"]
            }
        ],
        "replacementGroups": {
            "{GROUP_ID}": ["{OPTION_ID}"]
        },
        "groupRequirements": {
            "{GROUP_ID}": [{"GROUP_ID"}]
        },
        "requirements": {
            "{OPTION_ID}": ["{OPTION_ID}"]
        },
        "incompatibilities": {
            "{OPTION_ID}": ["{OPTION_ID}"]
        },
        "priceList": {
            "{OPTION_ID}": Number
        }
    ]
}
```
**Todo:**
- [x] get the products configuration information from the database api
- [x] format the data in the correct way and send it as a response 

**Test cases:**
- [x] test response data

## /configuration (POST)
> to save a new configuration with its configuration options for a new product

**Request Data:**
```javascript
{
    "configId": String,
    "name": String,
    "description": String,
    "images": [String],
    "options": [
        {
            "id": Number,
            "name": String,
            "description": String
        }
    ],
    "optionGroups": [
        {
            "id": String,
            "name": String,
            "description": String,
            "optionIds": [Number],
            "required": Boolean,
            "replacement": Boolean
        }
    ],
    "rules": {
        "basePrice": Number,
        "defaultModel": "{MODEL_NAME}",
        "models:": [
            {
                "model": String,
                "options": ["{OPTION_ID}"]
            }
        ],
        "requirements": {
            "{OPTION_ID}": ["{OPTION_ID}"]
        },
        "incompatibilities": {
            "{OPTION_ID}": ["{OPTION_ID}"]
        },
        "priceList": {
            "{OPTION_ID}": Number
        },
    },
    "languages": {
        "{LANGUAGE_NAME}": {
            "name": String,
            "description": String,
            "options": [
                {
                    "id": String,
                    "name": String,
                    "description": String,
                }
            ],
            "optionSections": [
                {
                    "id": String,
                    "name": String
                }
            ],
            "optionGroups": [
                {
                    "id": String,
                    "name": String,
                    "description": String
                }
            ]
        }
    }
}
```
**Response Data:**
```javascript
{

}
```
**Todo:**
- [x] destruct the json object into the format that the database api wants it
- [x] send the data to the database api

**Test cases:**
- [x] check if the json is correctly read and reformatted

**Comment by dominik-pm** [comment]
@t-scherzer hab mal beim post "replacementgroups" gelöscht und an Boolean für de Gruppe eingefügt
